apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp44
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp4400
      port: 44400
      targetPort: 44400
      protocol: UDP
    - name : udp4401
      port: 44401
      targetPort: 44401
      protocol: UDP
    - name : udp4402
      port: 44402
      targetPort: 44402
      protocol: UDP
    - name : udp4403
      port: 44403
      targetPort: 44403
      protocol: UDP
    - name : udp4404
      port: 44404
      targetPort: 44404
      protocol: UDP
    - name : udp4405
      port: 44405
      targetPort: 44405
      protocol: UDP
    - name : udp4406
      port: 44406
      targetPort: 44406
      protocol: UDP
    - name : udp4407
      port: 44407
      targetPort: 44407
      protocol: UDP
    - name : udp4408
      port: 44408
      targetPort: 44408
      protocol: UDP
    - name : udp4409
      port: 44409
      targetPort: 44409
      protocol: UDP
    - name : udp4410
      port: 44410
      targetPort: 44410
      protocol: UDP
    - name : udp4411
      port: 44411
      targetPort: 44411
      protocol: UDP
    - name : udp4412
      port: 44412
      targetPort: 44412
      protocol: UDP
    - name : udp4413
      port: 44413
      targetPort: 44413
      protocol: UDP
    - name : udp4414
      port: 44414
      targetPort: 44414
      protocol: UDP
    - name : udp4415
      port: 44415
      targetPort: 44415
      protocol: UDP
    - name : udp4416
      port: 44416
      targetPort: 44416
      protocol: UDP
    - name : udp4417
      port: 44417
      targetPort: 44417
      protocol: UDP
    - name : udp4418
      port: 44418
      targetPort: 44418
      protocol: UDP
    - name : udp4419
      port: 44419
      targetPort: 44419
      protocol: UDP
    - name : udp4420
      port: 44420
      targetPort: 44420
      protocol: UDP
    - name : udp4421
      port: 44421
      targetPort: 44421
      protocol: UDP
    - name : udp4422
      port: 44422
      targetPort: 44422
      protocol: UDP
    - name : udp4423
      port: 44423
      targetPort: 44423
      protocol: UDP
    - name : udp4424
      port: 44424
      targetPort: 44424
      protocol: UDP
    - name : udp4425
      port: 44425
      targetPort: 44425
      protocol: UDP
    - name : udp4426
      port: 44426
      targetPort: 44426
      protocol: UDP
    - name : udp4427
      port: 44427
      targetPort: 44427
      protocol: UDP
    - name : udp4428
      port: 44428
      targetPort: 44428
      protocol: UDP
    - name : udp4429
      port: 44429
      targetPort: 44429
      protocol: UDP
    - name : udp4430
      port: 44430
      targetPort: 44430
      protocol: UDP
    - name : udp4431
      port: 44431
      targetPort: 44431
      protocol: UDP
    - name : udp4432
      port: 44432
      targetPort: 44432
      protocol: UDP
    - name : udp4433
      port: 44433
      targetPort: 44433
      protocol: UDP
    - name : udp4434
      port: 44434
      targetPort: 44434
      protocol: UDP
    - name : udp4435
      port: 44435
      targetPort: 44435
      protocol: UDP
    - name : udp4436
      port: 44436
      targetPort: 44436
      protocol: UDP
    - name : udp4437
      port: 44437
      targetPort: 44437
      protocol: UDP
    - name : udp4438
      port: 44438
      targetPort: 44438
      protocol: UDP
    - name : udp4439
      port: 44439
      targetPort: 44439
      protocol: UDP
    - name : udp4440
      port: 44440
      targetPort: 44440
      protocol: UDP
    - name : udp4441
      port: 44441
      targetPort: 44441
      protocol: UDP
    - name : udp4442
      port: 44442
      targetPort: 44442
      protocol: UDP
    - name : udp4443
      port: 44443
      targetPort: 44443
      protocol: UDP
    - name : udp4444
      port: 44444
      targetPort: 44444
      protocol: UDP
    - name : udp4445
      port: 44445
      targetPort: 44445
      protocol: UDP
    - name : udp4446
      port: 44446
      targetPort: 44446
      protocol: UDP
    - name : udp4447
      port: 44447
      targetPort: 44447
      protocol: UDP
    - name : udp4448
      port: 44448
      targetPort: 44448
      protocol: UDP
    - name : udp4449
      port: 44449
      targetPort: 44449
      protocol: UDP
    - name : udp4450
      port: 44450
      targetPort: 44450
      protocol: UDP
    - name : udp4451
      port: 44451
      targetPort: 44451
      protocol: UDP
    - name : udp4452
      port: 44452
      targetPort: 44452
      protocol: UDP
    - name : udp4453
      port: 44453
      targetPort: 44453
      protocol: UDP
    - name : udp4454
      port: 44454
      targetPort: 44454
      protocol: UDP
    - name : udp4455
      port: 44455
      targetPort: 44455
      protocol: UDP
    - name : udp4456
      port: 44456
      targetPort: 44456
      protocol: UDP
    - name : udp4457
      port: 44457
      targetPort: 44457
      protocol: UDP
    - name : udp4458
      port: 44458
      targetPort: 44458
      protocol: UDP
    - name : udp4459
      port: 44459
      targetPort: 44459
      protocol: UDP
    - name : udp4460
      port: 44460
      targetPort: 44460
      protocol: UDP
    - name : udp4461
      port: 44461
      targetPort: 44461
      protocol: UDP
    - name : udp4462
      port: 44462
      targetPort: 44462
      protocol: UDP
    - name : udp4463
      port: 44463
      targetPort: 44463
      protocol: UDP
    - name : udp4464
      port: 44464
      targetPort: 44464
      protocol: UDP
    - name : udp4465
      port: 44465
      targetPort: 44465
      protocol: UDP
    - name : udp4466
      port: 44466
      targetPort: 44466
      protocol: UDP
    - name : udp4467
      port: 44467
      targetPort: 44467
      protocol: UDP
    - name : udp4468
      port: 44468
      targetPort: 44468
      protocol: UDP
    - name : udp4469
      port: 44469
      targetPort: 44469
      protocol: UDP
    - name : udp4470
      port: 44470
      targetPort: 44470
      protocol: UDP
    - name : udp4471
      port: 44471
      targetPort: 44471
      protocol: UDP
    - name : udp4472
      port: 44472
      targetPort: 44472
      protocol: UDP
    - name : udp4473
      port: 44473
      targetPort: 44473
      protocol: UDP
    - name : udp4474
      port: 44474
      targetPort: 44474
      protocol: UDP
    - name : udp4475
      port: 44475
      targetPort: 44475
      protocol: UDP
    - name : udp4476
      port: 44476
      targetPort: 44476
      protocol: UDP
    - name : udp4477
      port: 44477
      targetPort: 44477
      protocol: UDP
    - name : udp4478
      port: 44478
      targetPort: 44478
      protocol: UDP
    - name : udp4479
      port: 44479
      targetPort: 44479
      protocol: UDP
    - name : udp4480
      port: 44480
      targetPort: 44480
      protocol: UDP
    - name : udp4481
      port: 44481
      targetPort: 44481
      protocol: UDP
    - name : udp4482
      port: 44482
      targetPort: 44482
      protocol: UDP
    - name : udp4483
      port: 44483
      targetPort: 44483
      protocol: UDP
    - name : udp4484
      port: 44484
      targetPort: 44484
      protocol: UDP
    - name : udp4485
      port: 44485
      targetPort: 44485
      protocol: UDP
    - name : udp4486
      port: 44486
      targetPort: 44486
      protocol: UDP
    - name : udp4487
      port: 44487
      targetPort: 44487
      protocol: UDP
    - name : udp4488
      port: 44488
      targetPort: 44488
      protocol: UDP
    - name : udp4489
      port: 44489
      targetPort: 44489
      protocol: UDP
    - name : udp4490
      port: 44490
      targetPort: 44490
      protocol: UDP
    - name : udp4491
      port: 44491
      targetPort: 44491
      protocol: UDP
    - name : udp4492
      port: 44492
      targetPort: 44492
      protocol: UDP
    - name : udp4493
      port: 44493
      targetPort: 44493
      protocol: UDP
    - name : udp4494
      port: 44494
      targetPort: 44494
      protocol: UDP
    - name : udp4495
      port: 44495
      targetPort: 44495
      protocol: UDP
    - name : udp4496
      port: 44496
      targetPort: 44496
      protocol: UDP
    - name : udp4497
      port: 44497
      targetPort: 44497
      protocol: UDP
    - name : udp4498
      port: 44498
      targetPort: 44498
      protocol: UDP
    - name : udp4499
      port: 44499
      targetPort: 44499
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
