apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp34
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp3400
      port: 43400
      targetPort: 43400
      protocol: UDP
    - name : udp3401
      port: 43401
      targetPort: 43401
      protocol: UDP
    - name : udp3402
      port: 43402
      targetPort: 43402
      protocol: UDP
    - name : udp3403
      port: 43403
      targetPort: 43403
      protocol: UDP
    - name : udp3404
      port: 43404
      targetPort: 43404
      protocol: UDP
    - name : udp3405
      port: 43405
      targetPort: 43405
      protocol: UDP
    - name : udp3406
      port: 43406
      targetPort: 43406
      protocol: UDP
    - name : udp3407
      port: 43407
      targetPort: 43407
      protocol: UDP
    - name : udp3408
      port: 43408
      targetPort: 43408
      protocol: UDP
    - name : udp3409
      port: 43409
      targetPort: 43409
      protocol: UDP
    - name : udp3410
      port: 43410
      targetPort: 43410
      protocol: UDP
    - name : udp3411
      port: 43411
      targetPort: 43411
      protocol: UDP
    - name : udp3412
      port: 43412
      targetPort: 43412
      protocol: UDP
    - name : udp3413
      port: 43413
      targetPort: 43413
      protocol: UDP
    - name : udp3414
      port: 43414
      targetPort: 43414
      protocol: UDP
    - name : udp3415
      port: 43415
      targetPort: 43415
      protocol: UDP
    - name : udp3416
      port: 43416
      targetPort: 43416
      protocol: UDP
    - name : udp3417
      port: 43417
      targetPort: 43417
      protocol: UDP
    - name : udp3418
      port: 43418
      targetPort: 43418
      protocol: UDP
    - name : udp3419
      port: 43419
      targetPort: 43419
      protocol: UDP
    - name : udp3420
      port: 43420
      targetPort: 43420
      protocol: UDP
    - name : udp3421
      port: 43421
      targetPort: 43421
      protocol: UDP
    - name : udp3422
      port: 43422
      targetPort: 43422
      protocol: UDP
    - name : udp3423
      port: 43423
      targetPort: 43423
      protocol: UDP
    - name : udp3424
      port: 43424
      targetPort: 43424
      protocol: UDP
    - name : udp3425
      port: 43425
      targetPort: 43425
      protocol: UDP
    - name : udp3426
      port: 43426
      targetPort: 43426
      protocol: UDP
    - name : udp3427
      port: 43427
      targetPort: 43427
      protocol: UDP
    - name : udp3428
      port: 43428
      targetPort: 43428
      protocol: UDP
    - name : udp3429
      port: 43429
      targetPort: 43429
      protocol: UDP
    - name : udp3430
      port: 43430
      targetPort: 43430
      protocol: UDP
    - name : udp3431
      port: 43431
      targetPort: 43431
      protocol: UDP
    - name : udp3432
      port: 43432
      targetPort: 43432
      protocol: UDP
    - name : udp3433
      port: 43433
      targetPort: 43433
      protocol: UDP
    - name : udp3434
      port: 43434
      targetPort: 43434
      protocol: UDP
    - name : udp3435
      port: 43435
      targetPort: 43435
      protocol: UDP
    - name : udp3436
      port: 43436
      targetPort: 43436
      protocol: UDP
    - name : udp3437
      port: 43437
      targetPort: 43437
      protocol: UDP
    - name : udp3438
      port: 43438
      targetPort: 43438
      protocol: UDP
    - name : udp3439
      port: 43439
      targetPort: 43439
      protocol: UDP
    - name : udp3440
      port: 43440
      targetPort: 43440
      protocol: UDP
    - name : udp3441
      port: 43441
      targetPort: 43441
      protocol: UDP
    - name : udp3442
      port: 43442
      targetPort: 43442
      protocol: UDP
    - name : udp3443
      port: 43443
      targetPort: 43443
      protocol: UDP
    - name : udp3444
      port: 43444
      targetPort: 43444
      protocol: UDP
    - name : udp3445
      port: 43445
      targetPort: 43445
      protocol: UDP
    - name : udp3446
      port: 43446
      targetPort: 43446
      protocol: UDP
    - name : udp3447
      port: 43447
      targetPort: 43447
      protocol: UDP
    - name : udp3448
      port: 43448
      targetPort: 43448
      protocol: UDP
    - name : udp3449
      port: 43449
      targetPort: 43449
      protocol: UDP
    - name : udp3450
      port: 43450
      targetPort: 43450
      protocol: UDP
    - name : udp3451
      port: 43451
      targetPort: 43451
      protocol: UDP
    - name : udp3452
      port: 43452
      targetPort: 43452
      protocol: UDP
    - name : udp3453
      port: 43453
      targetPort: 43453
      protocol: UDP
    - name : udp3454
      port: 43454
      targetPort: 43454
      protocol: UDP
    - name : udp3455
      port: 43455
      targetPort: 43455
      protocol: UDP
    - name : udp3456
      port: 43456
      targetPort: 43456
      protocol: UDP
    - name : udp3457
      port: 43457
      targetPort: 43457
      protocol: UDP
    - name : udp3458
      port: 43458
      targetPort: 43458
      protocol: UDP
    - name : udp3459
      port: 43459
      targetPort: 43459
      protocol: UDP
    - name : udp3460
      port: 43460
      targetPort: 43460
      protocol: UDP
    - name : udp3461
      port: 43461
      targetPort: 43461
      protocol: UDP
    - name : udp3462
      port: 43462
      targetPort: 43462
      protocol: UDP
    - name : udp3463
      port: 43463
      targetPort: 43463
      protocol: UDP
    - name : udp3464
      port: 43464
      targetPort: 43464
      protocol: UDP
    - name : udp3465
      port: 43465
      targetPort: 43465
      protocol: UDP
    - name : udp3466
      port: 43466
      targetPort: 43466
      protocol: UDP
    - name : udp3467
      port: 43467
      targetPort: 43467
      protocol: UDP
    - name : udp3468
      port: 43468
      targetPort: 43468
      protocol: UDP
    - name : udp3469
      port: 43469
      targetPort: 43469
      protocol: UDP
    - name : udp3470
      port: 43470
      targetPort: 43470
      protocol: UDP
    - name : udp3471
      port: 43471
      targetPort: 43471
      protocol: UDP
    - name : udp3472
      port: 43472
      targetPort: 43472
      protocol: UDP
    - name : udp3473
      port: 43473
      targetPort: 43473
      protocol: UDP
    - name : udp3474
      port: 43474
      targetPort: 43474
      protocol: UDP
    - name : udp3475
      port: 43475
      targetPort: 43475
      protocol: UDP
    - name : udp3476
      port: 43476
      targetPort: 43476
      protocol: UDP
    - name : udp3477
      port: 43477
      targetPort: 43477
      protocol: UDP
    - name : udp3478
      port: 43478
      targetPort: 43478
      protocol: UDP
    - name : udp3479
      port: 43479
      targetPort: 43479
      protocol: UDP
    - name : udp3480
      port: 43480
      targetPort: 43480
      protocol: UDP
    - name : udp3481
      port: 43481
      targetPort: 43481
      protocol: UDP
    - name : udp3482
      port: 43482
      targetPort: 43482
      protocol: UDP
    - name : udp3483
      port: 43483
      targetPort: 43483
      protocol: UDP
    - name : udp3484
      port: 43484
      targetPort: 43484
      protocol: UDP
    - name : udp3485
      port: 43485
      targetPort: 43485
      protocol: UDP
    - name : udp3486
      port: 43486
      targetPort: 43486
      protocol: UDP
    - name : udp3487
      port: 43487
      targetPort: 43487
      protocol: UDP
    - name : udp3488
      port: 43488
      targetPort: 43488
      protocol: UDP
    - name : udp3489
      port: 43489
      targetPort: 43489
      protocol: UDP
    - name : udp3490
      port: 43490
      targetPort: 43490
      protocol: UDP
    - name : udp3491
      port: 43491
      targetPort: 43491
      protocol: UDP
    - name : udp3492
      port: 43492
      targetPort: 43492
      protocol: UDP
    - name : udp3493
      port: 43493
      targetPort: 43493
      protocol: UDP
    - name : udp3494
      port: 43494
      targetPort: 43494
      protocol: UDP
    - name : udp3495
      port: 43495
      targetPort: 43495
      protocol: UDP
    - name : udp3496
      port: 43496
      targetPort: 43496
      protocol: UDP
    - name : udp3497
      port: 43497
      targetPort: 43497
      protocol: UDP
    - name : udp3498
      port: 43498
      targetPort: 43498
      protocol: UDP
    - name : udp3499
      port: 43499
      targetPort: 43499
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
