apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp31
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp3100
      port: 43100
      targetPort: 43100
      protocol: UDP
    - name : udp3101
      port: 43101
      targetPort: 43101
      protocol: UDP
    - name : udp3102
      port: 43102
      targetPort: 43102
      protocol: UDP
    - name : udp3103
      port: 43103
      targetPort: 43103
      protocol: UDP
    - name : udp3104
      port: 43104
      targetPort: 43104
      protocol: UDP
    - name : udp3105
      port: 43105
      targetPort: 43105
      protocol: UDP
    - name : udp3106
      port: 43106
      targetPort: 43106
      protocol: UDP
    - name : udp3107
      port: 43107
      targetPort: 43107
      protocol: UDP
    - name : udp3108
      port: 43108
      targetPort: 43108
      protocol: UDP
    - name : udp3109
      port: 43109
      targetPort: 43109
      protocol: UDP
    - name : udp3110
      port: 43110
      targetPort: 43110
      protocol: UDP
    - name : udp3111
      port: 43111
      targetPort: 43111
      protocol: UDP
    - name : udp3112
      port: 43112
      targetPort: 43112
      protocol: UDP
    - name : udp3113
      port: 43113
      targetPort: 43113
      protocol: UDP
    - name : udp3114
      port: 43114
      targetPort: 43114
      protocol: UDP
    - name : udp3115
      port: 43115
      targetPort: 43115
      protocol: UDP
    - name : udp3116
      port: 43116
      targetPort: 43116
      protocol: UDP
    - name : udp3117
      port: 43117
      targetPort: 43117
      protocol: UDP
    - name : udp3118
      port: 43118
      targetPort: 43118
      protocol: UDP
    - name : udp3119
      port: 43119
      targetPort: 43119
      protocol: UDP
    - name : udp3120
      port: 43120
      targetPort: 43120
      protocol: UDP
    - name : udp3121
      port: 43121
      targetPort: 43121
      protocol: UDP
    - name : udp3122
      port: 43122
      targetPort: 43122
      protocol: UDP
    - name : udp3123
      port: 43123
      targetPort: 43123
      protocol: UDP
    - name : udp3124
      port: 43124
      targetPort: 43124
      protocol: UDP
    - name : udp3125
      port: 43125
      targetPort: 43125
      protocol: UDP
    - name : udp3126
      port: 43126
      targetPort: 43126
      protocol: UDP
    - name : udp3127
      port: 43127
      targetPort: 43127
      protocol: UDP
    - name : udp3128
      port: 43128
      targetPort: 43128
      protocol: UDP
    - name : udp3129
      port: 43129
      targetPort: 43129
      protocol: UDP
    - name : udp3130
      port: 43130
      targetPort: 43130
      protocol: UDP
    - name : udp3131
      port: 43131
      targetPort: 43131
      protocol: UDP
    - name : udp3132
      port: 43132
      targetPort: 43132
      protocol: UDP
    - name : udp3133
      port: 43133
      targetPort: 43133
      protocol: UDP
    - name : udp3134
      port: 43134
      targetPort: 43134
      protocol: UDP
    - name : udp3135
      port: 43135
      targetPort: 43135
      protocol: UDP
    - name : udp3136
      port: 43136
      targetPort: 43136
      protocol: UDP
    - name : udp3137
      port: 43137
      targetPort: 43137
      protocol: UDP
    - name : udp3138
      port: 43138
      targetPort: 43138
      protocol: UDP
    - name : udp3139
      port: 43139
      targetPort: 43139
      protocol: UDP
    - name : udp3140
      port: 43140
      targetPort: 43140
      protocol: UDP
    - name : udp3141
      port: 43141
      targetPort: 43141
      protocol: UDP
    - name : udp3142
      port: 43142
      targetPort: 43142
      protocol: UDP
    - name : udp3143
      port: 43143
      targetPort: 43143
      protocol: UDP
    - name : udp3144
      port: 43144
      targetPort: 43144
      protocol: UDP
    - name : udp3145
      port: 43145
      targetPort: 43145
      protocol: UDP
    - name : udp3146
      port: 43146
      targetPort: 43146
      protocol: UDP
    - name : udp3147
      port: 43147
      targetPort: 43147
      protocol: UDP
    - name : udp3148
      port: 43148
      targetPort: 43148
      protocol: UDP
    - name : udp3149
      port: 43149
      targetPort: 43149
      protocol: UDP
    - name : udp3150
      port: 43150
      targetPort: 43150
      protocol: UDP
    - name : udp3151
      port: 43151
      targetPort: 43151
      protocol: UDP
    - name : udp3152
      port: 43152
      targetPort: 43152
      protocol: UDP
    - name : udp3153
      port: 43153
      targetPort: 43153
      protocol: UDP
    - name : udp3154
      port: 43154
      targetPort: 43154
      protocol: UDP
    - name : udp3155
      port: 43155
      targetPort: 43155
      protocol: UDP
    - name : udp3156
      port: 43156
      targetPort: 43156
      protocol: UDP
    - name : udp3157
      port: 43157
      targetPort: 43157
      protocol: UDP
    - name : udp3158
      port: 43158
      targetPort: 43158
      protocol: UDP
    - name : udp3159
      port: 43159
      targetPort: 43159
      protocol: UDP
    - name : udp3160
      port: 43160
      targetPort: 43160
      protocol: UDP
    - name : udp3161
      port: 43161
      targetPort: 43161
      protocol: UDP
    - name : udp3162
      port: 43162
      targetPort: 43162
      protocol: UDP
    - name : udp3163
      port: 43163
      targetPort: 43163
      protocol: UDP
    - name : udp3164
      port: 43164
      targetPort: 43164
      protocol: UDP
    - name : udp3165
      port: 43165
      targetPort: 43165
      protocol: UDP
    - name : udp3166
      port: 43166
      targetPort: 43166
      protocol: UDP
    - name : udp3167
      port: 43167
      targetPort: 43167
      protocol: UDP
    - name : udp3168
      port: 43168
      targetPort: 43168
      protocol: UDP
    - name : udp3169
      port: 43169
      targetPort: 43169
      protocol: UDP
    - name : udp3170
      port: 43170
      targetPort: 43170
      protocol: UDP
    - name : udp3171
      port: 43171
      targetPort: 43171
      protocol: UDP
    - name : udp3172
      port: 43172
      targetPort: 43172
      protocol: UDP
    - name : udp3173
      port: 43173
      targetPort: 43173
      protocol: UDP
    - name : udp3174
      port: 43174
      targetPort: 43174
      protocol: UDP
    - name : udp3175
      port: 43175
      targetPort: 43175
      protocol: UDP
    - name : udp3176
      port: 43176
      targetPort: 43176
      protocol: UDP
    - name : udp3177
      port: 43177
      targetPort: 43177
      protocol: UDP
    - name : udp3178
      port: 43178
      targetPort: 43178
      protocol: UDP
    - name : udp3179
      port: 43179
      targetPort: 43179
      protocol: UDP
    - name : udp3180
      port: 43180
      targetPort: 43180
      protocol: UDP
    - name : udp3181
      port: 43181
      targetPort: 43181
      protocol: UDP
    - name : udp3182
      port: 43182
      targetPort: 43182
      protocol: UDP
    - name : udp3183
      port: 43183
      targetPort: 43183
      protocol: UDP
    - name : udp3184
      port: 43184
      targetPort: 43184
      protocol: UDP
    - name : udp3185
      port: 43185
      targetPort: 43185
      protocol: UDP
    - name : udp3186
      port: 43186
      targetPort: 43186
      protocol: UDP
    - name : udp3187
      port: 43187
      targetPort: 43187
      protocol: UDP
    - name : udp3188
      port: 43188
      targetPort: 43188
      protocol: UDP
    - name : udp3189
      port: 43189
      targetPort: 43189
      protocol: UDP
    - name : udp3190
      port: 43190
      targetPort: 43190
      protocol: UDP
    - name : udp3191
      port: 43191
      targetPort: 43191
      protocol: UDP
    - name : udp3192
      port: 43192
      targetPort: 43192
      protocol: UDP
    - name : udp3193
      port: 43193
      targetPort: 43193
      protocol: UDP
    - name : udp3194
      port: 43194
      targetPort: 43194
      protocol: UDP
    - name : udp3195
      port: 43195
      targetPort: 43195
      protocol: UDP
    - name : udp3196
      port: 43196
      targetPort: 43196
      protocol: UDP
    - name : udp3197
      port: 43197
      targetPort: 43197
      protocol: UDP
    - name : udp3198
      port: 43198
      targetPort: 43198
      protocol: UDP
    - name : udp3199
      port: 43199
      targetPort: 43199
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
