apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp81
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp8100
      port: 48100
      targetPort: 48100
      protocol: UDP
    - name : udp8101
      port: 48101
      targetPort: 48101
      protocol: UDP
    - name : udp8102
      port: 48102
      targetPort: 48102
      protocol: UDP
    - name : udp8103
      port: 48103
      targetPort: 48103
      protocol: UDP
    - name : udp8104
      port: 48104
      targetPort: 48104
      protocol: UDP
    - name : udp8105
      port: 48105
      targetPort: 48105
      protocol: UDP
    - name : udp8106
      port: 48106
      targetPort: 48106
      protocol: UDP
    - name : udp8107
      port: 48107
      targetPort: 48107
      protocol: UDP
    - name : udp8108
      port: 48108
      targetPort: 48108
      protocol: UDP
    - name : udp8109
      port: 48109
      targetPort: 48109
      protocol: UDP
    - name : udp8110
      port: 48110
      targetPort: 48110
      protocol: UDP
    - name : udp8111
      port: 48111
      targetPort: 48111
      protocol: UDP
    - name : udp8112
      port: 48112
      targetPort: 48112
      protocol: UDP
    - name : udp8113
      port: 48113
      targetPort: 48113
      protocol: UDP
    - name : udp8114
      port: 48114
      targetPort: 48114
      protocol: UDP
    - name : udp8115
      port: 48115
      targetPort: 48115
      protocol: UDP
    - name : udp8116
      port: 48116
      targetPort: 48116
      protocol: UDP
    - name : udp8117
      port: 48117
      targetPort: 48117
      protocol: UDP
    - name : udp8118
      port: 48118
      targetPort: 48118
      protocol: UDP
    - name : udp8119
      port: 48119
      targetPort: 48119
      protocol: UDP
    - name : udp8120
      port: 48120
      targetPort: 48120
      protocol: UDP
    - name : udp8121
      port: 48121
      targetPort: 48121
      protocol: UDP
    - name : udp8122
      port: 48122
      targetPort: 48122
      protocol: UDP
    - name : udp8123
      port: 48123
      targetPort: 48123
      protocol: UDP
    - name : udp8124
      port: 48124
      targetPort: 48124
      protocol: UDP
    - name : udp8125
      port: 48125
      targetPort: 48125
      protocol: UDP
    - name : udp8126
      port: 48126
      targetPort: 48126
      protocol: UDP
    - name : udp8127
      port: 48127
      targetPort: 48127
      protocol: UDP
    - name : udp8128
      port: 48128
      targetPort: 48128
      protocol: UDP
    - name : udp8129
      port: 48129
      targetPort: 48129
      protocol: UDP
    - name : udp8130
      port: 48130
      targetPort: 48130
      protocol: UDP
    - name : udp8131
      port: 48131
      targetPort: 48131
      protocol: UDP
    - name : udp8132
      port: 48132
      targetPort: 48132
      protocol: UDP
    - name : udp8133
      port: 48133
      targetPort: 48133
      protocol: UDP
    - name : udp8134
      port: 48134
      targetPort: 48134
      protocol: UDP
    - name : udp8135
      port: 48135
      targetPort: 48135
      protocol: UDP
    - name : udp8136
      port: 48136
      targetPort: 48136
      protocol: UDP
    - name : udp8137
      port: 48137
      targetPort: 48137
      protocol: UDP
    - name : udp8138
      port: 48138
      targetPort: 48138
      protocol: UDP
    - name : udp8139
      port: 48139
      targetPort: 48139
      protocol: UDP
    - name : udp8140
      port: 48140
      targetPort: 48140
      protocol: UDP
    - name : udp8141
      port: 48141
      targetPort: 48141
      protocol: UDP
    - name : udp8142
      port: 48142
      targetPort: 48142
      protocol: UDP
    - name : udp8143
      port: 48143
      targetPort: 48143
      protocol: UDP
    - name : udp8144
      port: 48144
      targetPort: 48144
      protocol: UDP
    - name : udp8145
      port: 48145
      targetPort: 48145
      protocol: UDP
    - name : udp8146
      port: 48146
      targetPort: 48146
      protocol: UDP
    - name : udp8147
      port: 48147
      targetPort: 48147
      protocol: UDP
    - name : udp8148
      port: 48148
      targetPort: 48148
      protocol: UDP
    - name : udp8149
      port: 48149
      targetPort: 48149
      protocol: UDP
    - name : udp8150
      port: 48150
      targetPort: 48150
      protocol: UDP
    - name : udp8151
      port: 48151
      targetPort: 48151
      protocol: UDP
    - name : udp8152
      port: 48152
      targetPort: 48152
      protocol: UDP
    - name : udp8153
      port: 48153
      targetPort: 48153
      protocol: UDP
    - name : udp8154
      port: 48154
      targetPort: 48154
      protocol: UDP
    - name : udp8155
      port: 48155
      targetPort: 48155
      protocol: UDP
    - name : udp8156
      port: 48156
      targetPort: 48156
      protocol: UDP
    - name : udp8157
      port: 48157
      targetPort: 48157
      protocol: UDP
    - name : udp8158
      port: 48158
      targetPort: 48158
      protocol: UDP
    - name : udp8159
      port: 48159
      targetPort: 48159
      protocol: UDP
    - name : udp8160
      port: 48160
      targetPort: 48160
      protocol: UDP
    - name : udp8161
      port: 48161
      targetPort: 48161
      protocol: UDP
    - name : udp8162
      port: 48162
      targetPort: 48162
      protocol: UDP
    - name : udp8163
      port: 48163
      targetPort: 48163
      protocol: UDP
    - name : udp8164
      port: 48164
      targetPort: 48164
      protocol: UDP
    - name : udp8165
      port: 48165
      targetPort: 48165
      protocol: UDP
    - name : udp8166
      port: 48166
      targetPort: 48166
      protocol: UDP
    - name : udp8167
      port: 48167
      targetPort: 48167
      protocol: UDP
    - name : udp8168
      port: 48168
      targetPort: 48168
      protocol: UDP
    - name : udp8169
      port: 48169
      targetPort: 48169
      protocol: UDP
    - name : udp8170
      port: 48170
      targetPort: 48170
      protocol: UDP
    - name : udp8171
      port: 48171
      targetPort: 48171
      protocol: UDP
    - name : udp8172
      port: 48172
      targetPort: 48172
      protocol: UDP
    - name : udp8173
      port: 48173
      targetPort: 48173
      protocol: UDP
    - name : udp8174
      port: 48174
      targetPort: 48174
      protocol: UDP
    - name : udp8175
      port: 48175
      targetPort: 48175
      protocol: UDP
    - name : udp8176
      port: 48176
      targetPort: 48176
      protocol: UDP
    - name : udp8177
      port: 48177
      targetPort: 48177
      protocol: UDP
    - name : udp8178
      port: 48178
      targetPort: 48178
      protocol: UDP
    - name : udp8179
      port: 48179
      targetPort: 48179
      protocol: UDP
    - name : udp8180
      port: 48180
      targetPort: 48180
      protocol: UDP
    - name : udp8181
      port: 48181
      targetPort: 48181
      protocol: UDP
    - name : udp8182
      port: 48182
      targetPort: 48182
      protocol: UDP
    - name : udp8183
      port: 48183
      targetPort: 48183
      protocol: UDP
    - name : udp8184
      port: 48184
      targetPort: 48184
      protocol: UDP
    - name : udp8185
      port: 48185
      targetPort: 48185
      protocol: UDP
    - name : udp8186
      port: 48186
      targetPort: 48186
      protocol: UDP
    - name : udp8187
      port: 48187
      targetPort: 48187
      protocol: UDP
    - name : udp8188
      port: 48188
      targetPort: 48188
      protocol: UDP
    - name : udp8189
      port: 48189
      targetPort: 48189
      protocol: UDP
    - name : udp8190
      port: 48190
      targetPort: 48190
      protocol: UDP
    - name : udp8191
      port: 48191
      targetPort: 48191
      protocol: UDP
    - name : udp8192
      port: 48192
      targetPort: 48192
      protocol: UDP
    - name : udp8193
      port: 48193
      targetPort: 48193
      protocol: UDP
    - name : udp8194
      port: 48194
      targetPort: 48194
      protocol: UDP
    - name : udp8195
      port: 48195
      targetPort: 48195
      protocol: UDP
    - name : udp8196
      port: 48196
      targetPort: 48196
      protocol: UDP
    - name : udp8197
      port: 48197
      targetPort: 48197
      protocol: UDP
    - name : udp8198
      port: 48198
      targetPort: 48198
      protocol: UDP
    - name : udp8199
      port: 48199
      targetPort: 48199
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
