apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp66
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp6600
      port: 46600
      targetPort: 46600
      protocol: UDP
    - name : udp6601
      port: 46601
      targetPort: 46601
      protocol: UDP
    - name : udp6602
      port: 46602
      targetPort: 46602
      protocol: UDP
    - name : udp6603
      port: 46603
      targetPort: 46603
      protocol: UDP
    - name : udp6604
      port: 46604
      targetPort: 46604
      protocol: UDP
    - name : udp6605
      port: 46605
      targetPort: 46605
      protocol: UDP
    - name : udp6606
      port: 46606
      targetPort: 46606
      protocol: UDP
    - name : udp6607
      port: 46607
      targetPort: 46607
      protocol: UDP
    - name : udp6608
      port: 46608
      targetPort: 46608
      protocol: UDP
    - name : udp6609
      port: 46609
      targetPort: 46609
      protocol: UDP
    - name : udp6610
      port: 46610
      targetPort: 46610
      protocol: UDP
    - name : udp6611
      port: 46611
      targetPort: 46611
      protocol: UDP
    - name : udp6612
      port: 46612
      targetPort: 46612
      protocol: UDP
    - name : udp6613
      port: 46613
      targetPort: 46613
      protocol: UDP
    - name : udp6614
      port: 46614
      targetPort: 46614
      protocol: UDP
    - name : udp6615
      port: 46615
      targetPort: 46615
      protocol: UDP
    - name : udp6616
      port: 46616
      targetPort: 46616
      protocol: UDP
    - name : udp6617
      port: 46617
      targetPort: 46617
      protocol: UDP
    - name : udp6618
      port: 46618
      targetPort: 46618
      protocol: UDP
    - name : udp6619
      port: 46619
      targetPort: 46619
      protocol: UDP
    - name : udp6620
      port: 46620
      targetPort: 46620
      protocol: UDP
    - name : udp6621
      port: 46621
      targetPort: 46621
      protocol: UDP
    - name : udp6622
      port: 46622
      targetPort: 46622
      protocol: UDP
    - name : udp6623
      port: 46623
      targetPort: 46623
      protocol: UDP
    - name : udp6624
      port: 46624
      targetPort: 46624
      protocol: UDP
    - name : udp6625
      port: 46625
      targetPort: 46625
      protocol: UDP
    - name : udp6626
      port: 46626
      targetPort: 46626
      protocol: UDP
    - name : udp6627
      port: 46627
      targetPort: 46627
      protocol: UDP
    - name : udp6628
      port: 46628
      targetPort: 46628
      protocol: UDP
    - name : udp6629
      port: 46629
      targetPort: 46629
      protocol: UDP
    - name : udp6630
      port: 46630
      targetPort: 46630
      protocol: UDP
    - name : udp6631
      port: 46631
      targetPort: 46631
      protocol: UDP
    - name : udp6632
      port: 46632
      targetPort: 46632
      protocol: UDP
    - name : udp6633
      port: 46633
      targetPort: 46633
      protocol: UDP
    - name : udp6634
      port: 46634
      targetPort: 46634
      protocol: UDP
    - name : udp6635
      port: 46635
      targetPort: 46635
      protocol: UDP
    - name : udp6636
      port: 46636
      targetPort: 46636
      protocol: UDP
    - name : udp6637
      port: 46637
      targetPort: 46637
      protocol: UDP
    - name : udp6638
      port: 46638
      targetPort: 46638
      protocol: UDP
    - name : udp6639
      port: 46639
      targetPort: 46639
      protocol: UDP
    - name : udp6640
      port: 46640
      targetPort: 46640
      protocol: UDP
    - name : udp6641
      port: 46641
      targetPort: 46641
      protocol: UDP
    - name : udp6642
      port: 46642
      targetPort: 46642
      protocol: UDP
    - name : udp6643
      port: 46643
      targetPort: 46643
      protocol: UDP
    - name : udp6644
      port: 46644
      targetPort: 46644
      protocol: UDP
    - name : udp6645
      port: 46645
      targetPort: 46645
      protocol: UDP
    - name : udp6646
      port: 46646
      targetPort: 46646
      protocol: UDP
    - name : udp6647
      port: 46647
      targetPort: 46647
      protocol: UDP
    - name : udp6648
      port: 46648
      targetPort: 46648
      protocol: UDP
    - name : udp6649
      port: 46649
      targetPort: 46649
      protocol: UDP
    - name : udp6650
      port: 46650
      targetPort: 46650
      protocol: UDP
    - name : udp6651
      port: 46651
      targetPort: 46651
      protocol: UDP
    - name : udp6652
      port: 46652
      targetPort: 46652
      protocol: UDP
    - name : udp6653
      port: 46653
      targetPort: 46653
      protocol: UDP
    - name : udp6654
      port: 46654
      targetPort: 46654
      protocol: UDP
    - name : udp6655
      port: 46655
      targetPort: 46655
      protocol: UDP
    - name : udp6656
      port: 46656
      targetPort: 46656
      protocol: UDP
    - name : udp6657
      port: 46657
      targetPort: 46657
      protocol: UDP
    - name : udp6658
      port: 46658
      targetPort: 46658
      protocol: UDP
    - name : udp6659
      port: 46659
      targetPort: 46659
      protocol: UDP
    - name : udp6660
      port: 46660
      targetPort: 46660
      protocol: UDP
    - name : udp6661
      port: 46661
      targetPort: 46661
      protocol: UDP
    - name : udp6662
      port: 46662
      targetPort: 46662
      protocol: UDP
    - name : udp6663
      port: 46663
      targetPort: 46663
      protocol: UDP
    - name : udp6664
      port: 46664
      targetPort: 46664
      protocol: UDP
    - name : udp6665
      port: 46665
      targetPort: 46665
      protocol: UDP
    - name : udp6666
      port: 46666
      targetPort: 46666
      protocol: UDP
    - name : udp6667
      port: 46667
      targetPort: 46667
      protocol: UDP
    - name : udp6668
      port: 46668
      targetPort: 46668
      protocol: UDP
    - name : udp6669
      port: 46669
      targetPort: 46669
      protocol: UDP
    - name : udp6670
      port: 46670
      targetPort: 46670
      protocol: UDP
    - name : udp6671
      port: 46671
      targetPort: 46671
      protocol: UDP
    - name : udp6672
      port: 46672
      targetPort: 46672
      protocol: UDP
    - name : udp6673
      port: 46673
      targetPort: 46673
      protocol: UDP
    - name : udp6674
      port: 46674
      targetPort: 46674
      protocol: UDP
    - name : udp6675
      port: 46675
      targetPort: 46675
      protocol: UDP
    - name : udp6676
      port: 46676
      targetPort: 46676
      protocol: UDP
    - name : udp6677
      port: 46677
      targetPort: 46677
      protocol: UDP
    - name : udp6678
      port: 46678
      targetPort: 46678
      protocol: UDP
    - name : udp6679
      port: 46679
      targetPort: 46679
      protocol: UDP
    - name : udp6680
      port: 46680
      targetPort: 46680
      protocol: UDP
    - name : udp6681
      port: 46681
      targetPort: 46681
      protocol: UDP
    - name : udp6682
      port: 46682
      targetPort: 46682
      protocol: UDP
    - name : udp6683
      port: 46683
      targetPort: 46683
      protocol: UDP
    - name : udp6684
      port: 46684
      targetPort: 46684
      protocol: UDP
    - name : udp6685
      port: 46685
      targetPort: 46685
      protocol: UDP
    - name : udp6686
      port: 46686
      targetPort: 46686
      protocol: UDP
    - name : udp6687
      port: 46687
      targetPort: 46687
      protocol: UDP
    - name : udp6688
      port: 46688
      targetPort: 46688
      protocol: UDP
    - name : udp6689
      port: 46689
      targetPort: 46689
      protocol: UDP
    - name : udp6690
      port: 46690
      targetPort: 46690
      protocol: UDP
    - name : udp6691
      port: 46691
      targetPort: 46691
      protocol: UDP
    - name : udp6692
      port: 46692
      targetPort: 46692
      protocol: UDP
    - name : udp6693
      port: 46693
      targetPort: 46693
      protocol: UDP
    - name : udp6694
      port: 46694
      targetPort: 46694
      protocol: UDP
    - name : udp6695
      port: 46695
      targetPort: 46695
      protocol: UDP
    - name : udp6696
      port: 46696
      targetPort: 46696
      protocol: UDP
    - name : udp6697
      port: 46697
      targetPort: 46697
      protocol: UDP
    - name : udp6698
      port: 46698
      targetPort: 46698
      protocol: UDP
    - name : udp6699
      port: 46699
      targetPort: 46699
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
