apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp63
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp6300
      port: 46300
      targetPort: 46300
      protocol: UDP
    - name : udp6301
      port: 46301
      targetPort: 46301
      protocol: UDP
    - name : udp6302
      port: 46302
      targetPort: 46302
      protocol: UDP
    - name : udp6303
      port: 46303
      targetPort: 46303
      protocol: UDP
    - name : udp6304
      port: 46304
      targetPort: 46304
      protocol: UDP
    - name : udp6305
      port: 46305
      targetPort: 46305
      protocol: UDP
    - name : udp6306
      port: 46306
      targetPort: 46306
      protocol: UDP
    - name : udp6307
      port: 46307
      targetPort: 46307
      protocol: UDP
    - name : udp6308
      port: 46308
      targetPort: 46308
      protocol: UDP
    - name : udp6309
      port: 46309
      targetPort: 46309
      protocol: UDP
    - name : udp6310
      port: 46310
      targetPort: 46310
      protocol: UDP
    - name : udp6311
      port: 46311
      targetPort: 46311
      protocol: UDP
    - name : udp6312
      port: 46312
      targetPort: 46312
      protocol: UDP
    - name : udp6313
      port: 46313
      targetPort: 46313
      protocol: UDP
    - name : udp6314
      port: 46314
      targetPort: 46314
      protocol: UDP
    - name : udp6315
      port: 46315
      targetPort: 46315
      protocol: UDP
    - name : udp6316
      port: 46316
      targetPort: 46316
      protocol: UDP
    - name : udp6317
      port: 46317
      targetPort: 46317
      protocol: UDP
    - name : udp6318
      port: 46318
      targetPort: 46318
      protocol: UDP
    - name : udp6319
      port: 46319
      targetPort: 46319
      protocol: UDP
    - name : udp6320
      port: 46320
      targetPort: 46320
      protocol: UDP
    - name : udp6321
      port: 46321
      targetPort: 46321
      protocol: UDP
    - name : udp6322
      port: 46322
      targetPort: 46322
      protocol: UDP
    - name : udp6323
      port: 46323
      targetPort: 46323
      protocol: UDP
    - name : udp6324
      port: 46324
      targetPort: 46324
      protocol: UDP
    - name : udp6325
      port: 46325
      targetPort: 46325
      protocol: UDP
    - name : udp6326
      port: 46326
      targetPort: 46326
      protocol: UDP
    - name : udp6327
      port: 46327
      targetPort: 46327
      protocol: UDP
    - name : udp6328
      port: 46328
      targetPort: 46328
      protocol: UDP
    - name : udp6329
      port: 46329
      targetPort: 46329
      protocol: UDP
    - name : udp6330
      port: 46330
      targetPort: 46330
      protocol: UDP
    - name : udp6331
      port: 46331
      targetPort: 46331
      protocol: UDP
    - name : udp6332
      port: 46332
      targetPort: 46332
      protocol: UDP
    - name : udp6333
      port: 46333
      targetPort: 46333
      protocol: UDP
    - name : udp6334
      port: 46334
      targetPort: 46334
      protocol: UDP
    - name : udp6335
      port: 46335
      targetPort: 46335
      protocol: UDP
    - name : udp6336
      port: 46336
      targetPort: 46336
      protocol: UDP
    - name : udp6337
      port: 46337
      targetPort: 46337
      protocol: UDP
    - name : udp6338
      port: 46338
      targetPort: 46338
      protocol: UDP
    - name : udp6339
      port: 46339
      targetPort: 46339
      protocol: UDP
    - name : udp6340
      port: 46340
      targetPort: 46340
      protocol: UDP
    - name : udp6341
      port: 46341
      targetPort: 46341
      protocol: UDP
    - name : udp6342
      port: 46342
      targetPort: 46342
      protocol: UDP
    - name : udp6343
      port: 46343
      targetPort: 46343
      protocol: UDP
    - name : udp6344
      port: 46344
      targetPort: 46344
      protocol: UDP
    - name : udp6345
      port: 46345
      targetPort: 46345
      protocol: UDP
    - name : udp6346
      port: 46346
      targetPort: 46346
      protocol: UDP
    - name : udp6347
      port: 46347
      targetPort: 46347
      protocol: UDP
    - name : udp6348
      port: 46348
      targetPort: 46348
      protocol: UDP
    - name : udp6349
      port: 46349
      targetPort: 46349
      protocol: UDP
    - name : udp6350
      port: 46350
      targetPort: 46350
      protocol: UDP
    - name : udp6351
      port: 46351
      targetPort: 46351
      protocol: UDP
    - name : udp6352
      port: 46352
      targetPort: 46352
      protocol: UDP
    - name : udp6353
      port: 46353
      targetPort: 46353
      protocol: UDP
    - name : udp6354
      port: 46354
      targetPort: 46354
      protocol: UDP
    - name : udp6355
      port: 46355
      targetPort: 46355
      protocol: UDP
    - name : udp6356
      port: 46356
      targetPort: 46356
      protocol: UDP
    - name : udp6357
      port: 46357
      targetPort: 46357
      protocol: UDP
    - name : udp6358
      port: 46358
      targetPort: 46358
      protocol: UDP
    - name : udp6359
      port: 46359
      targetPort: 46359
      protocol: UDP
    - name : udp6360
      port: 46360
      targetPort: 46360
      protocol: UDP
    - name : udp6361
      port: 46361
      targetPort: 46361
      protocol: UDP
    - name : udp6362
      port: 46362
      targetPort: 46362
      protocol: UDP
    - name : udp6363
      port: 46363
      targetPort: 46363
      protocol: UDP
    - name : udp6364
      port: 46364
      targetPort: 46364
      protocol: UDP
    - name : udp6365
      port: 46365
      targetPort: 46365
      protocol: UDP
    - name : udp6366
      port: 46366
      targetPort: 46366
      protocol: UDP
    - name : udp6367
      port: 46367
      targetPort: 46367
      protocol: UDP
    - name : udp6368
      port: 46368
      targetPort: 46368
      protocol: UDP
    - name : udp6369
      port: 46369
      targetPort: 46369
      protocol: UDP
    - name : udp6370
      port: 46370
      targetPort: 46370
      protocol: UDP
    - name : udp6371
      port: 46371
      targetPort: 46371
      protocol: UDP
    - name : udp6372
      port: 46372
      targetPort: 46372
      protocol: UDP
    - name : udp6373
      port: 46373
      targetPort: 46373
      protocol: UDP
    - name : udp6374
      port: 46374
      targetPort: 46374
      protocol: UDP
    - name : udp6375
      port: 46375
      targetPort: 46375
      protocol: UDP
    - name : udp6376
      port: 46376
      targetPort: 46376
      protocol: UDP
    - name : udp6377
      port: 46377
      targetPort: 46377
      protocol: UDP
    - name : udp6378
      port: 46378
      targetPort: 46378
      protocol: UDP
    - name : udp6379
      port: 46379
      targetPort: 46379
      protocol: UDP
    - name : udp6380
      port: 46380
      targetPort: 46380
      protocol: UDP
    - name : udp6381
      port: 46381
      targetPort: 46381
      protocol: UDP
    - name : udp6382
      port: 46382
      targetPort: 46382
      protocol: UDP
    - name : udp6383
      port: 46383
      targetPort: 46383
      protocol: UDP
    - name : udp6384
      port: 46384
      targetPort: 46384
      protocol: UDP
    - name : udp6385
      port: 46385
      targetPort: 46385
      protocol: UDP
    - name : udp6386
      port: 46386
      targetPort: 46386
      protocol: UDP
    - name : udp6387
      port: 46387
      targetPort: 46387
      protocol: UDP
    - name : udp6388
      port: 46388
      targetPort: 46388
      protocol: UDP
    - name : udp6389
      port: 46389
      targetPort: 46389
      protocol: UDP
    - name : udp6390
      port: 46390
      targetPort: 46390
      protocol: UDP
    - name : udp6391
      port: 46391
      targetPort: 46391
      protocol: UDP
    - name : udp6392
      port: 46392
      targetPort: 46392
      protocol: UDP
    - name : udp6393
      port: 46393
      targetPort: 46393
      protocol: UDP
    - name : udp6394
      port: 46394
      targetPort: 46394
      protocol: UDP
    - name : udp6395
      port: 46395
      targetPort: 46395
      protocol: UDP
    - name : udp6396
      port: 46396
      targetPort: 46396
      protocol: UDP
    - name : udp6397
      port: 46397
      targetPort: 46397
      protocol: UDP
    - name : udp6398
      port: 46398
      targetPort: 46398
      protocol: UDP
    - name : udp6399
      port: 46399
      targetPort: 46399
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
