apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp86
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp8600
      port: 48600
      targetPort: 48600
      protocol: UDP
    - name : udp8601
      port: 48601
      targetPort: 48601
      protocol: UDP
    - name : udp8602
      port: 48602
      targetPort: 48602
      protocol: UDP
    - name : udp8603
      port: 48603
      targetPort: 48603
      protocol: UDP
    - name : udp8604
      port: 48604
      targetPort: 48604
      protocol: UDP
    - name : udp8605
      port: 48605
      targetPort: 48605
      protocol: UDP
    - name : udp8606
      port: 48606
      targetPort: 48606
      protocol: UDP
    - name : udp8607
      port: 48607
      targetPort: 48607
      protocol: UDP
    - name : udp8608
      port: 48608
      targetPort: 48608
      protocol: UDP
    - name : udp8609
      port: 48609
      targetPort: 48609
      protocol: UDP
    - name : udp8610
      port: 48610
      targetPort: 48610
      protocol: UDP
    - name : udp8611
      port: 48611
      targetPort: 48611
      protocol: UDP
    - name : udp8612
      port: 48612
      targetPort: 48612
      protocol: UDP
    - name : udp8613
      port: 48613
      targetPort: 48613
      protocol: UDP
    - name : udp8614
      port: 48614
      targetPort: 48614
      protocol: UDP
    - name : udp8615
      port: 48615
      targetPort: 48615
      protocol: UDP
    - name : udp8616
      port: 48616
      targetPort: 48616
      protocol: UDP
    - name : udp8617
      port: 48617
      targetPort: 48617
      protocol: UDP
    - name : udp8618
      port: 48618
      targetPort: 48618
      protocol: UDP
    - name : udp8619
      port: 48619
      targetPort: 48619
      protocol: UDP
    - name : udp8620
      port: 48620
      targetPort: 48620
      protocol: UDP
    - name : udp8621
      port: 48621
      targetPort: 48621
      protocol: UDP
    - name : udp8622
      port: 48622
      targetPort: 48622
      protocol: UDP
    - name : udp8623
      port: 48623
      targetPort: 48623
      protocol: UDP
    - name : udp8624
      port: 48624
      targetPort: 48624
      protocol: UDP
    - name : udp8625
      port: 48625
      targetPort: 48625
      protocol: UDP
    - name : udp8626
      port: 48626
      targetPort: 48626
      protocol: UDP
    - name : udp8627
      port: 48627
      targetPort: 48627
      protocol: UDP
    - name : udp8628
      port: 48628
      targetPort: 48628
      protocol: UDP
    - name : udp8629
      port: 48629
      targetPort: 48629
      protocol: UDP
    - name : udp8630
      port: 48630
      targetPort: 48630
      protocol: UDP
    - name : udp8631
      port: 48631
      targetPort: 48631
      protocol: UDP
    - name : udp8632
      port: 48632
      targetPort: 48632
      protocol: UDP
    - name : udp8633
      port: 48633
      targetPort: 48633
      protocol: UDP
    - name : udp8634
      port: 48634
      targetPort: 48634
      protocol: UDP
    - name : udp8635
      port: 48635
      targetPort: 48635
      protocol: UDP
    - name : udp8636
      port: 48636
      targetPort: 48636
      protocol: UDP
    - name : udp8637
      port: 48637
      targetPort: 48637
      protocol: UDP
    - name : udp8638
      port: 48638
      targetPort: 48638
      protocol: UDP
    - name : udp8639
      port: 48639
      targetPort: 48639
      protocol: UDP
    - name : udp8640
      port: 48640
      targetPort: 48640
      protocol: UDP
    - name : udp8641
      port: 48641
      targetPort: 48641
      protocol: UDP
    - name : udp8642
      port: 48642
      targetPort: 48642
      protocol: UDP
    - name : udp8643
      port: 48643
      targetPort: 48643
      protocol: UDP
    - name : udp8644
      port: 48644
      targetPort: 48644
      protocol: UDP
    - name : udp8645
      port: 48645
      targetPort: 48645
      protocol: UDP
    - name : udp8646
      port: 48646
      targetPort: 48646
      protocol: UDP
    - name : udp8647
      port: 48647
      targetPort: 48647
      protocol: UDP
    - name : udp8648
      port: 48648
      targetPort: 48648
      protocol: UDP
    - name : udp8649
      port: 48649
      targetPort: 48649
      protocol: UDP
    - name : udp8650
      port: 48650
      targetPort: 48650
      protocol: UDP
    - name : udp8651
      port: 48651
      targetPort: 48651
      protocol: UDP
    - name : udp8652
      port: 48652
      targetPort: 48652
      protocol: UDP
    - name : udp8653
      port: 48653
      targetPort: 48653
      protocol: UDP
    - name : udp8654
      port: 48654
      targetPort: 48654
      protocol: UDP
    - name : udp8655
      port: 48655
      targetPort: 48655
      protocol: UDP
    - name : udp8656
      port: 48656
      targetPort: 48656
      protocol: UDP
    - name : udp8657
      port: 48657
      targetPort: 48657
      protocol: UDP
    - name : udp8658
      port: 48658
      targetPort: 48658
      protocol: UDP
    - name : udp8659
      port: 48659
      targetPort: 48659
      protocol: UDP
    - name : udp8660
      port: 48660
      targetPort: 48660
      protocol: UDP
    - name : udp8661
      port: 48661
      targetPort: 48661
      protocol: UDP
    - name : udp8662
      port: 48662
      targetPort: 48662
      protocol: UDP
    - name : udp8663
      port: 48663
      targetPort: 48663
      protocol: UDP
    - name : udp8664
      port: 48664
      targetPort: 48664
      protocol: UDP
    - name : udp8665
      port: 48665
      targetPort: 48665
      protocol: UDP
    - name : udp8666
      port: 48666
      targetPort: 48666
      protocol: UDP
    - name : udp8667
      port: 48667
      targetPort: 48667
      protocol: UDP
    - name : udp8668
      port: 48668
      targetPort: 48668
      protocol: UDP
    - name : udp8669
      port: 48669
      targetPort: 48669
      protocol: UDP
    - name : udp8670
      port: 48670
      targetPort: 48670
      protocol: UDP
    - name : udp8671
      port: 48671
      targetPort: 48671
      protocol: UDP
    - name : udp8672
      port: 48672
      targetPort: 48672
      protocol: UDP
    - name : udp8673
      port: 48673
      targetPort: 48673
      protocol: UDP
    - name : udp8674
      port: 48674
      targetPort: 48674
      protocol: UDP
    - name : udp8675
      port: 48675
      targetPort: 48675
      protocol: UDP
    - name : udp8676
      port: 48676
      targetPort: 48676
      protocol: UDP
    - name : udp8677
      port: 48677
      targetPort: 48677
      protocol: UDP
    - name : udp8678
      port: 48678
      targetPort: 48678
      protocol: UDP
    - name : udp8679
      port: 48679
      targetPort: 48679
      protocol: UDP
    - name : udp8680
      port: 48680
      targetPort: 48680
      protocol: UDP
    - name : udp8681
      port: 48681
      targetPort: 48681
      protocol: UDP
    - name : udp8682
      port: 48682
      targetPort: 48682
      protocol: UDP
    - name : udp8683
      port: 48683
      targetPort: 48683
      protocol: UDP
    - name : udp8684
      port: 48684
      targetPort: 48684
      protocol: UDP
    - name : udp8685
      port: 48685
      targetPort: 48685
      protocol: UDP
    - name : udp8686
      port: 48686
      targetPort: 48686
      protocol: UDP
    - name : udp8687
      port: 48687
      targetPort: 48687
      protocol: UDP
    - name : udp8688
      port: 48688
      targetPort: 48688
      protocol: UDP
    - name : udp8689
      port: 48689
      targetPort: 48689
      protocol: UDP
    - name : udp8690
      port: 48690
      targetPort: 48690
      protocol: UDP
    - name : udp8691
      port: 48691
      targetPort: 48691
      protocol: UDP
    - name : udp8692
      port: 48692
      targetPort: 48692
      protocol: UDP
    - name : udp8693
      port: 48693
      targetPort: 48693
      protocol: UDP
    - name : udp8694
      port: 48694
      targetPort: 48694
      protocol: UDP
    - name : udp8695
      port: 48695
      targetPort: 48695
      protocol: UDP
    - name : udp8696
      port: 48696
      targetPort: 48696
      protocol: UDP
    - name : udp8697
      port: 48697
      targetPort: 48697
      protocol: UDP
    - name : udp8698
      port: 48698
      targetPort: 48698
      protocol: UDP
    - name : udp8699
      port: 48699
      targetPort: 48699
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
