apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp28
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp2800
      port: 42800
      targetPort: 42800
      protocol: UDP
    - name : udp2801
      port: 42801
      targetPort: 42801
      protocol: UDP
    - name : udp2802
      port: 42802
      targetPort: 42802
      protocol: UDP
    - name : udp2803
      port: 42803
      targetPort: 42803
      protocol: UDP
    - name : udp2804
      port: 42804
      targetPort: 42804
      protocol: UDP
    - name : udp2805
      port: 42805
      targetPort: 42805
      protocol: UDP
    - name : udp2806
      port: 42806
      targetPort: 42806
      protocol: UDP
    - name : udp2807
      port: 42807
      targetPort: 42807
      protocol: UDP
    - name : udp2808
      port: 42808
      targetPort: 42808
      protocol: UDP
    - name : udp2809
      port: 42809
      targetPort: 42809
      protocol: UDP
    - name : udp2810
      port: 42810
      targetPort: 42810
      protocol: UDP
    - name : udp2811
      port: 42811
      targetPort: 42811
      protocol: UDP
    - name : udp2812
      port: 42812
      targetPort: 42812
      protocol: UDP
    - name : udp2813
      port: 42813
      targetPort: 42813
      protocol: UDP
    - name : udp2814
      port: 42814
      targetPort: 42814
      protocol: UDP
    - name : udp2815
      port: 42815
      targetPort: 42815
      protocol: UDP
    - name : udp2816
      port: 42816
      targetPort: 42816
      protocol: UDP
    - name : udp2817
      port: 42817
      targetPort: 42817
      protocol: UDP
    - name : udp2818
      port: 42818
      targetPort: 42818
      protocol: UDP
    - name : udp2819
      port: 42819
      targetPort: 42819
      protocol: UDP
    - name : udp2820
      port: 42820
      targetPort: 42820
      protocol: UDP
    - name : udp2821
      port: 42821
      targetPort: 42821
      protocol: UDP
    - name : udp2822
      port: 42822
      targetPort: 42822
      protocol: UDP
    - name : udp2823
      port: 42823
      targetPort: 42823
      protocol: UDP
    - name : udp2824
      port: 42824
      targetPort: 42824
      protocol: UDP
    - name : udp2825
      port: 42825
      targetPort: 42825
      protocol: UDP
    - name : udp2826
      port: 42826
      targetPort: 42826
      protocol: UDP
    - name : udp2827
      port: 42827
      targetPort: 42827
      protocol: UDP
    - name : udp2828
      port: 42828
      targetPort: 42828
      protocol: UDP
    - name : udp2829
      port: 42829
      targetPort: 42829
      protocol: UDP
    - name : udp2830
      port: 42830
      targetPort: 42830
      protocol: UDP
    - name : udp2831
      port: 42831
      targetPort: 42831
      protocol: UDP
    - name : udp2832
      port: 42832
      targetPort: 42832
      protocol: UDP
    - name : udp2833
      port: 42833
      targetPort: 42833
      protocol: UDP
    - name : udp2834
      port: 42834
      targetPort: 42834
      protocol: UDP
    - name : udp2835
      port: 42835
      targetPort: 42835
      protocol: UDP
    - name : udp2836
      port: 42836
      targetPort: 42836
      protocol: UDP
    - name : udp2837
      port: 42837
      targetPort: 42837
      protocol: UDP
    - name : udp2838
      port: 42838
      targetPort: 42838
      protocol: UDP
    - name : udp2839
      port: 42839
      targetPort: 42839
      protocol: UDP
    - name : udp2840
      port: 42840
      targetPort: 42840
      protocol: UDP
    - name : udp2841
      port: 42841
      targetPort: 42841
      protocol: UDP
    - name : udp2842
      port: 42842
      targetPort: 42842
      protocol: UDP
    - name : udp2843
      port: 42843
      targetPort: 42843
      protocol: UDP
    - name : udp2844
      port: 42844
      targetPort: 42844
      protocol: UDP
    - name : udp2845
      port: 42845
      targetPort: 42845
      protocol: UDP
    - name : udp2846
      port: 42846
      targetPort: 42846
      protocol: UDP
    - name : udp2847
      port: 42847
      targetPort: 42847
      protocol: UDP
    - name : udp2848
      port: 42848
      targetPort: 42848
      protocol: UDP
    - name : udp2849
      port: 42849
      targetPort: 42849
      protocol: UDP
    - name : udp2850
      port: 42850
      targetPort: 42850
      protocol: UDP
    - name : udp2851
      port: 42851
      targetPort: 42851
      protocol: UDP
    - name : udp2852
      port: 42852
      targetPort: 42852
      protocol: UDP
    - name : udp2853
      port: 42853
      targetPort: 42853
      protocol: UDP
    - name : udp2854
      port: 42854
      targetPort: 42854
      protocol: UDP
    - name : udp2855
      port: 42855
      targetPort: 42855
      protocol: UDP
    - name : udp2856
      port: 42856
      targetPort: 42856
      protocol: UDP
    - name : udp2857
      port: 42857
      targetPort: 42857
      protocol: UDP
    - name : udp2858
      port: 42858
      targetPort: 42858
      protocol: UDP
    - name : udp2859
      port: 42859
      targetPort: 42859
      protocol: UDP
    - name : udp2860
      port: 42860
      targetPort: 42860
      protocol: UDP
    - name : udp2861
      port: 42861
      targetPort: 42861
      protocol: UDP
    - name : udp2862
      port: 42862
      targetPort: 42862
      protocol: UDP
    - name : udp2863
      port: 42863
      targetPort: 42863
      protocol: UDP
    - name : udp2864
      port: 42864
      targetPort: 42864
      protocol: UDP
    - name : udp2865
      port: 42865
      targetPort: 42865
      protocol: UDP
    - name : udp2866
      port: 42866
      targetPort: 42866
      protocol: UDP
    - name : udp2867
      port: 42867
      targetPort: 42867
      protocol: UDP
    - name : udp2868
      port: 42868
      targetPort: 42868
      protocol: UDP
    - name : udp2869
      port: 42869
      targetPort: 42869
      protocol: UDP
    - name : udp2870
      port: 42870
      targetPort: 42870
      protocol: UDP
    - name : udp2871
      port: 42871
      targetPort: 42871
      protocol: UDP
    - name : udp2872
      port: 42872
      targetPort: 42872
      protocol: UDP
    - name : udp2873
      port: 42873
      targetPort: 42873
      protocol: UDP
    - name : udp2874
      port: 42874
      targetPort: 42874
      protocol: UDP
    - name : udp2875
      port: 42875
      targetPort: 42875
      protocol: UDP
    - name : udp2876
      port: 42876
      targetPort: 42876
      protocol: UDP
    - name : udp2877
      port: 42877
      targetPort: 42877
      protocol: UDP
    - name : udp2878
      port: 42878
      targetPort: 42878
      protocol: UDP
    - name : udp2879
      port: 42879
      targetPort: 42879
      protocol: UDP
    - name : udp2880
      port: 42880
      targetPort: 42880
      protocol: UDP
    - name : udp2881
      port: 42881
      targetPort: 42881
      protocol: UDP
    - name : udp2882
      port: 42882
      targetPort: 42882
      protocol: UDP
    - name : udp2883
      port: 42883
      targetPort: 42883
      protocol: UDP
    - name : udp2884
      port: 42884
      targetPort: 42884
      protocol: UDP
    - name : udp2885
      port: 42885
      targetPort: 42885
      protocol: UDP
    - name : udp2886
      port: 42886
      targetPort: 42886
      protocol: UDP
    - name : udp2887
      port: 42887
      targetPort: 42887
      protocol: UDP
    - name : udp2888
      port: 42888
      targetPort: 42888
      protocol: UDP
    - name : udp2889
      port: 42889
      targetPort: 42889
      protocol: UDP
    - name : udp2890
      port: 42890
      targetPort: 42890
      protocol: UDP
    - name : udp2891
      port: 42891
      targetPort: 42891
      protocol: UDP
    - name : udp2892
      port: 42892
      targetPort: 42892
      protocol: UDP
    - name : udp2893
      port: 42893
      targetPort: 42893
      protocol: UDP
    - name : udp2894
      port: 42894
      targetPort: 42894
      protocol: UDP
    - name : udp2895
      port: 42895
      targetPort: 42895
      protocol: UDP
    - name : udp2896
      port: 42896
      targetPort: 42896
      protocol: UDP
    - name : udp2897
      port: 42897
      targetPort: 42897
      protocol: UDP
    - name : udp2898
      port: 42898
      targetPort: 42898
      protocol: UDP
    - name : udp2899
      port: 42899
      targetPort: 42899
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
