apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp64
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp6400
      port: 46400
      targetPort: 46400
      protocol: UDP
    - name : udp6401
      port: 46401
      targetPort: 46401
      protocol: UDP
    - name : udp6402
      port: 46402
      targetPort: 46402
      protocol: UDP
    - name : udp6403
      port: 46403
      targetPort: 46403
      protocol: UDP
    - name : udp6404
      port: 46404
      targetPort: 46404
      protocol: UDP
    - name : udp6405
      port: 46405
      targetPort: 46405
      protocol: UDP
    - name : udp6406
      port: 46406
      targetPort: 46406
      protocol: UDP
    - name : udp6407
      port: 46407
      targetPort: 46407
      protocol: UDP
    - name : udp6408
      port: 46408
      targetPort: 46408
      protocol: UDP
    - name : udp6409
      port: 46409
      targetPort: 46409
      protocol: UDP
    - name : udp6410
      port: 46410
      targetPort: 46410
      protocol: UDP
    - name : udp6411
      port: 46411
      targetPort: 46411
      protocol: UDP
    - name : udp6412
      port: 46412
      targetPort: 46412
      protocol: UDP
    - name : udp6413
      port: 46413
      targetPort: 46413
      protocol: UDP
    - name : udp6414
      port: 46414
      targetPort: 46414
      protocol: UDP
    - name : udp6415
      port: 46415
      targetPort: 46415
      protocol: UDP
    - name : udp6416
      port: 46416
      targetPort: 46416
      protocol: UDP
    - name : udp6417
      port: 46417
      targetPort: 46417
      protocol: UDP
    - name : udp6418
      port: 46418
      targetPort: 46418
      protocol: UDP
    - name : udp6419
      port: 46419
      targetPort: 46419
      protocol: UDP
    - name : udp6420
      port: 46420
      targetPort: 46420
      protocol: UDP
    - name : udp6421
      port: 46421
      targetPort: 46421
      protocol: UDP
    - name : udp6422
      port: 46422
      targetPort: 46422
      protocol: UDP
    - name : udp6423
      port: 46423
      targetPort: 46423
      protocol: UDP
    - name : udp6424
      port: 46424
      targetPort: 46424
      protocol: UDP
    - name : udp6425
      port: 46425
      targetPort: 46425
      protocol: UDP
    - name : udp6426
      port: 46426
      targetPort: 46426
      protocol: UDP
    - name : udp6427
      port: 46427
      targetPort: 46427
      protocol: UDP
    - name : udp6428
      port: 46428
      targetPort: 46428
      protocol: UDP
    - name : udp6429
      port: 46429
      targetPort: 46429
      protocol: UDP
    - name : udp6430
      port: 46430
      targetPort: 46430
      protocol: UDP
    - name : udp6431
      port: 46431
      targetPort: 46431
      protocol: UDP
    - name : udp6432
      port: 46432
      targetPort: 46432
      protocol: UDP
    - name : udp6433
      port: 46433
      targetPort: 46433
      protocol: UDP
    - name : udp6434
      port: 46434
      targetPort: 46434
      protocol: UDP
    - name : udp6435
      port: 46435
      targetPort: 46435
      protocol: UDP
    - name : udp6436
      port: 46436
      targetPort: 46436
      protocol: UDP
    - name : udp6437
      port: 46437
      targetPort: 46437
      protocol: UDP
    - name : udp6438
      port: 46438
      targetPort: 46438
      protocol: UDP
    - name : udp6439
      port: 46439
      targetPort: 46439
      protocol: UDP
    - name : udp6440
      port: 46440
      targetPort: 46440
      protocol: UDP
    - name : udp6441
      port: 46441
      targetPort: 46441
      protocol: UDP
    - name : udp6442
      port: 46442
      targetPort: 46442
      protocol: UDP
    - name : udp6443
      port: 46443
      targetPort: 46443
      protocol: UDP
    - name : udp6444
      port: 46444
      targetPort: 46444
      protocol: UDP
    - name : udp6445
      port: 46445
      targetPort: 46445
      protocol: UDP
    - name : udp6446
      port: 46446
      targetPort: 46446
      protocol: UDP
    - name : udp6447
      port: 46447
      targetPort: 46447
      protocol: UDP
    - name : udp6448
      port: 46448
      targetPort: 46448
      protocol: UDP
    - name : udp6449
      port: 46449
      targetPort: 46449
      protocol: UDP
    - name : udp6450
      port: 46450
      targetPort: 46450
      protocol: UDP
    - name : udp6451
      port: 46451
      targetPort: 46451
      protocol: UDP
    - name : udp6452
      port: 46452
      targetPort: 46452
      protocol: UDP
    - name : udp6453
      port: 46453
      targetPort: 46453
      protocol: UDP
    - name : udp6454
      port: 46454
      targetPort: 46454
      protocol: UDP
    - name : udp6455
      port: 46455
      targetPort: 46455
      protocol: UDP
    - name : udp6456
      port: 46456
      targetPort: 46456
      protocol: UDP
    - name : udp6457
      port: 46457
      targetPort: 46457
      protocol: UDP
    - name : udp6458
      port: 46458
      targetPort: 46458
      protocol: UDP
    - name : udp6459
      port: 46459
      targetPort: 46459
      protocol: UDP
    - name : udp6460
      port: 46460
      targetPort: 46460
      protocol: UDP
    - name : udp6461
      port: 46461
      targetPort: 46461
      protocol: UDP
    - name : udp6462
      port: 46462
      targetPort: 46462
      protocol: UDP
    - name : udp6463
      port: 46463
      targetPort: 46463
      protocol: UDP
    - name : udp6464
      port: 46464
      targetPort: 46464
      protocol: UDP
    - name : udp6465
      port: 46465
      targetPort: 46465
      protocol: UDP
    - name : udp6466
      port: 46466
      targetPort: 46466
      protocol: UDP
    - name : udp6467
      port: 46467
      targetPort: 46467
      protocol: UDP
    - name : udp6468
      port: 46468
      targetPort: 46468
      protocol: UDP
    - name : udp6469
      port: 46469
      targetPort: 46469
      protocol: UDP
    - name : udp6470
      port: 46470
      targetPort: 46470
      protocol: UDP
    - name : udp6471
      port: 46471
      targetPort: 46471
      protocol: UDP
    - name : udp6472
      port: 46472
      targetPort: 46472
      protocol: UDP
    - name : udp6473
      port: 46473
      targetPort: 46473
      protocol: UDP
    - name : udp6474
      port: 46474
      targetPort: 46474
      protocol: UDP
    - name : udp6475
      port: 46475
      targetPort: 46475
      protocol: UDP
    - name : udp6476
      port: 46476
      targetPort: 46476
      protocol: UDP
    - name : udp6477
      port: 46477
      targetPort: 46477
      protocol: UDP
    - name : udp6478
      port: 46478
      targetPort: 46478
      protocol: UDP
    - name : udp6479
      port: 46479
      targetPort: 46479
      protocol: UDP
    - name : udp6480
      port: 46480
      targetPort: 46480
      protocol: UDP
    - name : udp6481
      port: 46481
      targetPort: 46481
      protocol: UDP
    - name : udp6482
      port: 46482
      targetPort: 46482
      protocol: UDP
    - name : udp6483
      port: 46483
      targetPort: 46483
      protocol: UDP
    - name : udp6484
      port: 46484
      targetPort: 46484
      protocol: UDP
    - name : udp6485
      port: 46485
      targetPort: 46485
      protocol: UDP
    - name : udp6486
      port: 46486
      targetPort: 46486
      protocol: UDP
    - name : udp6487
      port: 46487
      targetPort: 46487
      protocol: UDP
    - name : udp6488
      port: 46488
      targetPort: 46488
      protocol: UDP
    - name : udp6489
      port: 46489
      targetPort: 46489
      protocol: UDP
    - name : udp6490
      port: 46490
      targetPort: 46490
      protocol: UDP
    - name : udp6491
      port: 46491
      targetPort: 46491
      protocol: UDP
    - name : udp6492
      port: 46492
      targetPort: 46492
      protocol: UDP
    - name : udp6493
      port: 46493
      targetPort: 46493
      protocol: UDP
    - name : udp6494
      port: 46494
      targetPort: 46494
      protocol: UDP
    - name : udp6495
      port: 46495
      targetPort: 46495
      protocol: UDP
    - name : udp6496
      port: 46496
      targetPort: 46496
      protocol: UDP
    - name : udp6497
      port: 46497
      targetPort: 46497
      protocol: UDP
    - name : udp6498
      port: 46498
      targetPort: 46498
      protocol: UDP
    - name : udp6499
      port: 46499
      targetPort: 46499
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
