apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  loadBalancerIP: 20.74.42.138
  ports:
    - name : tcp
      port: {{ .Values.service.port }}
      targetPort: 3001
      protocol: TCP

  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
    