apiVersion: v1
kind: Service
metadata:
  name: {{ include "mediaserver.fullname" . }}-udp62
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
  annotations:
     metallb.universe.tf/allow-shared-ip: crowdwire
spec:
  type: LoadBalancer
  #loadBalancerIP: 193.136.92.151
  loadBalancerIP: 10.0.12.47
  #externalTrafficPolicy: Local
  ports:
    - name : udp6200
      port: 46200
      targetPort: 46200
      protocol: UDP
    - name : udp6201
      port: 46201
      targetPort: 46201
      protocol: UDP
    - name : udp6202
      port: 46202
      targetPort: 46202
      protocol: UDP
    - name : udp6203
      port: 46203
      targetPort: 46203
      protocol: UDP
    - name : udp6204
      port: 46204
      targetPort: 46204
      protocol: UDP
    - name : udp6205
      port: 46205
      targetPort: 46205
      protocol: UDP
    - name : udp6206
      port: 46206
      targetPort: 46206
      protocol: UDP
    - name : udp6207
      port: 46207
      targetPort: 46207
      protocol: UDP
    - name : udp6208
      port: 46208
      targetPort: 46208
      protocol: UDP
    - name : udp6209
      port: 46209
      targetPort: 46209
      protocol: UDP
    - name : udp6210
      port: 46210
      targetPort: 46210
      protocol: UDP
    - name : udp6211
      port: 46211
      targetPort: 46211
      protocol: UDP
    - name : udp6212
      port: 46212
      targetPort: 46212
      protocol: UDP
    - name : udp6213
      port: 46213
      targetPort: 46213
      protocol: UDP
    - name : udp6214
      port: 46214
      targetPort: 46214
      protocol: UDP
    - name : udp6215
      port: 46215
      targetPort: 46215
      protocol: UDP
    - name : udp6216
      port: 46216
      targetPort: 46216
      protocol: UDP
    - name : udp6217
      port: 46217
      targetPort: 46217
      protocol: UDP
    - name : udp6218
      port: 46218
      targetPort: 46218
      protocol: UDP
    - name : udp6219
      port: 46219
      targetPort: 46219
      protocol: UDP
    - name : udp6220
      port: 46220
      targetPort: 46220
      protocol: UDP
    - name : udp6221
      port: 46221
      targetPort: 46221
      protocol: UDP
    - name : udp6222
      port: 46222
      targetPort: 46222
      protocol: UDP
    - name : udp6223
      port: 46223
      targetPort: 46223
      protocol: UDP
    - name : udp6224
      port: 46224
      targetPort: 46224
      protocol: UDP
    - name : udp6225
      port: 46225
      targetPort: 46225
      protocol: UDP
    - name : udp6226
      port: 46226
      targetPort: 46226
      protocol: UDP
    - name : udp6227
      port: 46227
      targetPort: 46227
      protocol: UDP
    - name : udp6228
      port: 46228
      targetPort: 46228
      protocol: UDP
    - name : udp6229
      port: 46229
      targetPort: 46229
      protocol: UDP
    - name : udp6230
      port: 46230
      targetPort: 46230
      protocol: UDP
    - name : udp6231
      port: 46231
      targetPort: 46231
      protocol: UDP
    - name : udp6232
      port: 46232
      targetPort: 46232
      protocol: UDP
    - name : udp6233
      port: 46233
      targetPort: 46233
      protocol: UDP
    - name : udp6234
      port: 46234
      targetPort: 46234
      protocol: UDP
    - name : udp6235
      port: 46235
      targetPort: 46235
      protocol: UDP
    - name : udp6236
      port: 46236
      targetPort: 46236
      protocol: UDP
    - name : udp6237
      port: 46237
      targetPort: 46237
      protocol: UDP
    - name : udp6238
      port: 46238
      targetPort: 46238
      protocol: UDP
    - name : udp6239
      port: 46239
      targetPort: 46239
      protocol: UDP
    - name : udp6240
      port: 46240
      targetPort: 46240
      protocol: UDP
    - name : udp6241
      port: 46241
      targetPort: 46241
      protocol: UDP
    - name : udp6242
      port: 46242
      targetPort: 46242
      protocol: UDP
    - name : udp6243
      port: 46243
      targetPort: 46243
      protocol: UDP
    - name : udp6244
      port: 46244
      targetPort: 46244
      protocol: UDP
    - name : udp6245
      port: 46245
      targetPort: 46245
      protocol: UDP
    - name : udp6246
      port: 46246
      targetPort: 46246
      protocol: UDP
    - name : udp6247
      port: 46247
      targetPort: 46247
      protocol: UDP
    - name : udp6248
      port: 46248
      targetPort: 46248
      protocol: UDP
    - name : udp6249
      port: 46249
      targetPort: 46249
      protocol: UDP
    - name : udp6250
      port: 46250
      targetPort: 46250
      protocol: UDP
    - name : udp6251
      port: 46251
      targetPort: 46251
      protocol: UDP
    - name : udp6252
      port: 46252
      targetPort: 46252
      protocol: UDP
    - name : udp6253
      port: 46253
      targetPort: 46253
      protocol: UDP
    - name : udp6254
      port: 46254
      targetPort: 46254
      protocol: UDP
    - name : udp6255
      port: 46255
      targetPort: 46255
      protocol: UDP
    - name : udp6256
      port: 46256
      targetPort: 46256
      protocol: UDP
    - name : udp6257
      port: 46257
      targetPort: 46257
      protocol: UDP
    - name : udp6258
      port: 46258
      targetPort: 46258
      protocol: UDP
    - name : udp6259
      port: 46259
      targetPort: 46259
      protocol: UDP
    - name : udp6260
      port: 46260
      targetPort: 46260
      protocol: UDP
    - name : udp6261
      port: 46261
      targetPort: 46261
      protocol: UDP
    - name : udp6262
      port: 46262
      targetPort: 46262
      protocol: UDP
    - name : udp6263
      port: 46263
      targetPort: 46263
      protocol: UDP
    - name : udp6264
      port: 46264
      targetPort: 46264
      protocol: UDP
    - name : udp6265
      port: 46265
      targetPort: 46265
      protocol: UDP
    - name : udp6266
      port: 46266
      targetPort: 46266
      protocol: UDP
    - name : udp6267
      port: 46267
      targetPort: 46267
      protocol: UDP
    - name : udp6268
      port: 46268
      targetPort: 46268
      protocol: UDP
    - name : udp6269
      port: 46269
      targetPort: 46269
      protocol: UDP
    - name : udp6270
      port: 46270
      targetPort: 46270
      protocol: UDP
    - name : udp6271
      port: 46271
      targetPort: 46271
      protocol: UDP
    - name : udp6272
      port: 46272
      targetPort: 46272
      protocol: UDP
    - name : udp6273
      port: 46273
      targetPort: 46273
      protocol: UDP
    - name : udp6274
      port: 46274
      targetPort: 46274
      protocol: UDP
    - name : udp6275
      port: 46275
      targetPort: 46275
      protocol: UDP
    - name : udp6276
      port: 46276
      targetPort: 46276
      protocol: UDP
    - name : udp6277
      port: 46277
      targetPort: 46277
      protocol: UDP
    - name : udp6278
      port: 46278
      targetPort: 46278
      protocol: UDP
    - name : udp6279
      port: 46279
      targetPort: 46279
      protocol: UDP
    - name : udp6280
      port: 46280
      targetPort: 46280
      protocol: UDP
    - name : udp6281
      port: 46281
      targetPort: 46281
      protocol: UDP
    - name : udp6282
      port: 46282
      targetPort: 46282
      protocol: UDP
    - name : udp6283
      port: 46283
      targetPort: 46283
      protocol: UDP
    - name : udp6284
      port: 46284
      targetPort: 46284
      protocol: UDP
    - name : udp6285
      port: 46285
      targetPort: 46285
      protocol: UDP
    - name : udp6286
      port: 46286
      targetPort: 46286
      protocol: UDP
    - name : udp6287
      port: 46287
      targetPort: 46287
      protocol: UDP
    - name : udp6288
      port: 46288
      targetPort: 46288
      protocol: UDP
    - name : udp6289
      port: 46289
      targetPort: 46289
      protocol: UDP
    - name : udp6290
      port: 46290
      targetPort: 46290
      protocol: UDP
    - name : udp6291
      port: 46291
      targetPort: 46291
      protocol: UDP
    - name : udp6292
      port: 46292
      targetPort: 46292
      protocol: UDP
    - name : udp6293
      port: 46293
      targetPort: 46293
      protocol: UDP
    - name : udp6294
      port: 46294
      targetPort: 46294
      protocol: UDP
    - name : udp6295
      port: 46295
      targetPort: 46295
      protocol: UDP
    - name : udp6296
      port: 46296
      targetPort: 46296
      protocol: UDP
    - name : udp6297
      port: 46297
      targetPort: 46297
      protocol: UDP
    - name : udp6298
      port: 46298
      targetPort: 46298
      protocol: UDP
    - name : udp6299
      port: 46299
      targetPort: 46299
      protocol: UDP
  selector:
    {{- include "mediaserver.selectorLabels" . | nindent 4 }}
