apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.servicename" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
      {{- if .Values.global.frontend.exposePort }}
    - port: {{ .Values.global.frontend.exposePort }}
      {{- else }}
    - port: {{ .Values.service.port }}
      {{- end }}
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
