# Errors
USER_NOT_IN_WORLD = "User is not registered in this world."
INVALID_CREDENTIALS = "Invalid email or password."
EMAIl_ALREADY_IN_USE = "A user with that email already exists."
INACTIVE_USER = "User is Inactive or the account has been banned."
INVALID_TAG = "Invalid Tag. Tag does not exist."
USER_NOT_PASSED = "User not passed as an argument."
ACCESS_FORBIDDEN = "Access Forbidden for Guests"
INVITATION_FORBIDDEN = "You do not have permission to generate invite links."
EDITION_FORBIDDEN = "You dont have access to edit this world or it does not exist."
WORLD_NOT_FOUND = "World Not Found or is not currently available."
USER_NOT_FOUND = "User with this id was not found"
USER_EDITION_FORBIDDEN = "You have no permission to edit this users account"
INVALID_USER_CREATION_STATUS = "Cannot register a user with that status"
ROLES_NOT_FOUND = "Role(s) Not Found for this World, or you do not have access to view" \
                  " add or update"
ROLE_NAME_NOT_FOUND = "Could not find a role with this name"
ROLE_NAME_ALREADY_IN_USE = "There is already a Role in this World, with this name "
ROLE_DEFAULT_ALREADY_EXISTS = "There is a default role for this World"
ROLE_DEFAULT_DELETE_FORBIDDEN = "Cannot delete the default role of a role"
GOOGLE_USER_ALREADY_REGISTERED = "This google account is already registered."
GOOGLE_EMAIL_ALREADY_REGISTERED = "There is already an account with this email."
# Success
USER_REGISTERED_SUCCESS = "User has been registered successfully."
AUTHENTICATION_SUCCESS = "Success Authenticating."
WORLD_CREATED_SUCCESS = "World Created Successfully"
WORLD_UPDATE_SUCCESS = "Success Updating World"
WORLD_DELETED_SUCCESS = "Success Deleting World"
ROLE_UPDATED_SUCCESS = "Success Updating Role"
ROLE_DELETED_SUCCESS = "Success Deleting Role"
ROLE_CHANGED_SUCCESS = "Changed Role with Success"
