apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: default
data:
  3001: default/crowdwire-mediaserver:3001
  40000: default/crowdwire-mediaserver:40000
  40001: default/crowdwire-mediaserver:40001
  40002: default/crowdwire-mediaserver:40002
  40003: default/crowdwire-mediaserver:40003
  40004: default/crowdwire-mediaserver:40004
  40005: default/crowdwire-mediaserver:40005
  40006: default/crowdwire-mediaserver:40006
  40007: default/crowdwire-mediaserver:40007
  40008: default/crowdwire-mediaserver:40008
  40009: default/crowdwire-mediaserver:40009
  40010: default/crowdwire-mediaserver:40010
  40011: default/crowdwire-mediaserver:40011
  40012: default/crowdwire-mediaserver:40012
  40013: default/crowdwire-mediaserver:40013
  40014: default/crowdwire-mediaserver:40014
  40015: default/crowdwire-mediaserver:40015
  40016: default/crowdwire-mediaserver:40016
  40017: default/crowdwire-mediaserver:40017
  40018: default/crowdwire-mediaserver:40018
  40019: default/crowdwire-mediaserver:40019
  40020: default/crowdwire-mediaserver:40020
  40021: default/crowdwire-mediaserver:40021
  40022: default/crowdwire-mediaserver:40022
  40023: default/crowdwire-mediaserver:40023
  40024: default/crowdwire-mediaserver:40024
  40025: default/crowdwire-mediaserver:40025
  40026: default/crowdwire-mediaserver:40026
  40027: default/crowdwire-mediaserver:40027
  40028: default/crowdwire-mediaserver:40028
  40029: default/crowdwire-mediaserver:40029
  40030: default/crowdwire-mediaserver:40030
  40031: default/crowdwire-mediaserver:40031
  40032: default/crowdwire-mediaserver:40032
  40033: default/crowdwire-mediaserver:40033
  40034: default/crowdwire-mediaserver:40034
  40035: default/crowdwire-mediaserver:40035
  40036: default/crowdwire-mediaserver:40036
  40037: default/crowdwire-mediaserver:40037
  40038: default/crowdwire-mediaserver:40038
  40039: default/crowdwire-mediaserver:40039
  40040: default/crowdwire-mediaserver:40040
  40041: default/crowdwire-mediaserver:40041
  40042: default/crowdwire-mediaserver:40042
  40043: default/crowdwire-mediaserver:40043
  40044: default/crowdwire-mediaserver:40044
  40045: default/crowdwire-mediaserver:40045
  40046: default/crowdwire-mediaserver:40046
  40047: default/crowdwire-mediaserver:40047
  40048: default/crowdwire-mediaserver:40048
  40049: default/crowdwire-mediaserver:40049