spec:
  template:
    spec:
      containers:
      - name: controller
        ports:
          - containerPort: 40000
            hostPort: 40000
            protocol: UDP
          - containerPort: 40001
            hostPort: 40001
            protocol: UDP
          - containerPort: 40002
            hostPort: 40002
            protocol: UDP
          - containerPort: 40003
            hostPort: 40003
            protocol: UDP
          - containerPort: 40004
            hostPort: 40004
            protocol: UDP
          - containerPort: 40005
            hostPort: 40005
            protocol: UDP
          - containerPort: 40006
            hostPort: 40006
            protocol: UDP
          - containerPort: 40007
            hostPort: 40007
            protocol: UDP
          - containerPort: 40008
            hostPort: 40008
            protocol: UDP
          - containerPort: 40009
            hostPort: 40009
            protocol: UDP
          - containerPort: 40010
            hostPort: 40010
            protocol: UDP
          - containerPort: 40011
            hostPort: 40011
            protocol: UDP
          - containerPort: 40012
            hostPort: 40012
            protocol: UDP
          - containerPort: 40013
            hostPort: 40013
            protocol: UDP
          - containerPort: 40014
            hostPort: 40014
            protocol: UDP
          - containerPort: 40015
            hostPort: 40015
            protocol: UDP
          - containerPort: 40016
            hostPort: 40016
            protocol: UDP
          - containerPort: 40017
            hostPort: 40017
            protocol: UDP
          - containerPort: 40018
            hostPort: 40018
            protocol: UDP
          - containerPort: 40019
            hostPort: 40019
            protocol: UDP
          - containerPort: 40020
            hostPort: 40020
            protocol: UDP
          - containerPort: 40021
            hostPort: 40021
            protocol: UDP
          - containerPort: 40022
            hostPort: 40022
            protocol: UDP
          - containerPort: 40023
            hostPort: 40023
            protocol: UDP
          - containerPort: 40024
            hostPort: 40024
            protocol: UDP
          - containerPort: 40025
            hostPort: 40025
            protocol: UDP
          - containerPort: 40026
            hostPort: 40026
            protocol: UDP
          - containerPort: 40027
            hostPort: 40027
            protocol: UDP
          - containerPort: 40028
            hostPort: 40028
            protocol: UDP
          - containerPort: 40029
            hostPort: 40029
            protocol: UDP
          - containerPort: 40030
            hostPort: 40030
            protocol: UDP
          - containerPort: 40031
            hostPort: 40031
            protocol: UDP
          - containerPort: 40032
            hostPort: 40032
            protocol: UDP
          - containerPort: 40033
            hostPort: 40033
            protocol: UDP
          - containerPort: 40034
            hostPort: 40034
            protocol: UDP
          - containerPort: 40035
            hostPort: 40035
            protocol: UDP
          - containerPort: 40036
            hostPort: 40036
            protocol: UDP
          - containerPort: 40037
            hostPort: 40037
            protocol: UDP
          - containerPort: 40038
            hostPort: 40038
            protocol: UDP
          - containerPort: 40039
            hostPort: 40039
            protocol: UDP
          - containerPort: 40040
            hostPort: 40040
            protocol: UDP
          - containerPort: 40041
            hostPort: 40041
            protocol: UDP
          - containerPort: 40042
            hostPort: 40042
            protocol: UDP
          - containerPort: 40043
            hostPort: 40043
            protocol: UDP
          - containerPort: 40044
            hostPort: 40044
            protocol: UDP
          - containerPort: 40045
            hostPort: 40045
            protocol: UDP
          - containerPort: 40046
            hostPort: 40046
            protocol: UDP
          - containerPort: 40047
            hostPort: 40047
            protocol: UDP
          - containerPort: 40048
            hostPort: 40048
            protocol: UDP
          - containerPort: 40049
            hostPort: 40049
            protocol: UDP