apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: ingress-nginx-3.10.1
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.41.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: udp-controller
  name: ingress-nginx-udp-controller
spec:
  type: LoadBalancer
  #loadBalancerIP: 20.74.40.44
  ports:
    - name : udp0
      port: 40000
      targetPort: 40000
      protocol: UDP
    - name : udp1
      port: 40001
      targetPort: 40001
      protocol: UDP
    - name : udp2
      port: 40002
      targetPort: 40002
      protocol: UDP
    - name : udp3
      port: 40003
      targetPort: 40003
      protocol: UDP
    - name : udp4
      port: 40004
      targetPort: 40004
      protocol: UDP
    - name : udp5
      port: 40005
      targetPort: 40005
      protocol: UDP
    - name : udp6
      port: 40006
      targetPort: 40006
      protocol: UDP
    - name : udp7
      port: 40007
      targetPort: 40007
      protocol: UDP
    - name : udp8
      port: 40008
      targetPort: 40008
      protocol: UDP
    - name : udp9
      port: 40009
      targetPort: 40009
      protocol: UDP
    - name : udp10
      port: 40010
      targetPort: 40010
      protocol: UDP
    - name : udp11
      port: 40011
      targetPort: 40011
      protocol: UDP
    - name : udp12
      port: 40012
      targetPort: 40012
      protocol: UDP
    - name : udp13
      port: 40013
      targetPort: 40013
      protocol: UDP
    - name : udp14
      port: 40014
      targetPort: 40014
      protocol: UDP
    - name : udp15
      port: 40015
      targetPort: 40015
      protocol: UDP
    - name : udp16
      port: 40016
      targetPort: 40016
      protocol: UDP
    - name : udp17
      port: 40017
      targetPort: 40017
      protocol: UDP
    - name : udp18
      port: 40018
      targetPort: 40018
      protocol: UDP
    - name : udp19
      port: 40019
      targetPort: 40019
      protocol: UDP
    - name : udp20
      port: 40020
      targetPort: 40020
      protocol: UDP
    - name : udp21
      port: 40021
      targetPort: 40021
      protocol: UDP
    - name : udp22
      port: 40022
      targetPort: 40022
      protocol: UDP
    - name : udp23
      port: 40023
      targetPort: 40023
      protocol: UDP
    - name : udp24
      port: 40024
      targetPort: 40024
      protocol: UDP
    - name : udp25
      port: 40025
      targetPort: 40025
      protocol: UDP
    - name : udp26
      port: 40026
      targetPort: 40026
      protocol: UDP
    - name : udp27
      port: 40027
      targetPort: 40027
      protocol: UDP
    - name : udp28
      port: 40028
      targetPort: 40028
      protocol: UDP
    - name : udp29
      port: 40029
      targetPort: 40029
      protocol: UDP
    - name : udp30
      port: 40030
      targetPort: 40030
      protocol: UDP
    - name : udp31
      port: 40031
      targetPort: 40031
      protocol: UDP
    - name : udp32
      port: 40032
      targetPort: 40032
      protocol: UDP
    - name : udp33
      port: 40033
      targetPort: 40033
      protocol: UDP
    - name : udp34
      port: 40034
      targetPort: 40034
      protocol: UDP
    - name : udp35
      port: 40035
      targetPort: 40035
      protocol: UDP
    - name : udp36
      port: 40036
      targetPort: 40036
      protocol: UDP
    - name : udp37
      port: 40037
      targetPort: 40037
      protocol: UDP
    - name : udp38
      port: 40038
      targetPort: 40038
      protocol: UDP
    - name : udp39
      port: 40039
      targetPort: 40039
      protocol: UDP
    - name : udp40
      port: 40040
      targetPort: 40040
      protocol: UDP
    - name : udp41
      port: 40041
      targetPort: 40041
      protocol: UDP
    - name : udp42
      port: 40042
      targetPort: 40042
      protocol: UDP
    - name : udp43
      port: 40043
      targetPort: 40043
      protocol: UDP
    - name : udp44
      port: 40044
      targetPort: 40044
      protocol: UDP
    - name : udp45
      port: 40045
      targetPort: 40045
      protocol: UDP
    - name : udp46
      port: 40046
      targetPort: 40046
      protocol: UDP
    - name : udp47
      port: 40047
      targetPort: 40047
      protocol: UDP
    - name : udp48
      port: 40048
      targetPort: 40048
      protocol: UDP
    - name : udp49
      port: 40049
      targetPort: 40049
      protocol: UDP

  

  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: udp-controller