version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.8
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
volumes:
  rabbitmq_data:
    driver: local
