apiVersion: v1
data:
  secretkey: RjVlQ0Z0VThxVTFGdU13WGEvMC9wcEF2V3ZBZ2lmd2UwUXhGM0NRNi9uQXNKdGpHSmwvWVl0dkdJWjUwYUFBago1QytyN1J5Wjk3cUF2SG9Lc1BYK1RJUXZiWVBQRDNJR0hiMms0RjFEUE0xamFCYTE1cDRycUNFU2k0ZmIvcm1DClJIeXRvTmxsaTVRdDNHekNoamhMVDhlY0VyM1daSWxub0lDbzBzaDZVN1U9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
