apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: my-ip-space
      protocol: layer2
      addresses:
       - 10.0.12.47 - 10.0.12.48
       # - 193.136.92.151/32
       # - 193.136.92.152/32
       # auto-assign: false

